Repository geekelo/personal-inventory, pull requests merged in 2023-09, with the labels that each got.

#40 Milestone1: Group Task and initial Set up
  .gitignore
  app.rb
  class/item.rb
  main.rb
Labels: Group Task

#41 Create Book & Label classes
  app.rb
  class/book.rb
  class/item.rb
  class/label.rb
  main.rb
Labels: Melkammu's Task

#42 Created MusicAlbum and Genre classes
  class/genre.rb
  class/item.rb
  class/music_album.rb
Labels: Ayomide's Task

#44 Milestones: Create Movies class
  .gitattribute
  .rubocop.yml
  class/book.rb
  class/game.rb
  class/item.rb
  class/movie.rb
  class/source.rb
  data/movies.json
  main.rb
Labels: Eloghene's Task

#49 Milestone: Fix bugs to localize movie and music title
  class/item.rb
  class/movie.rb
  class/music_album.rb
  data/movies.json
  data/music_album.json
  spec/genre_spec.rb
  spec/items_spec.rb
  spec/source_spec.rb
Labels: Eloghene's Task

#50 Implement Game & Author methods
  class/author.rb
  class/game.rb
Labels: Chandan's Task

#51 Implement methods for Book & Label
  class/book.rb
  schema.sql
Labels: Melkammu's Task

#52 Add unit tests for all implemented methods of Game & Author
  README.md
  spec/author_spec.rb
  spec/game_spec.rb
Labels: Chandan's Task

#53 Add unit tests for Book & Label methods
  class/book.rb
  class/label.rb
  spec/book_spec.rb
  spec/label_spec.rb
Labels: Melkammu's Task

#54 Milestone: Add readme & Fix bugs
  MIT.md
  README.md
  data/movies.json
  data/music_album.json
Labels: Eloghene's Task

#55 Add Options for Game & Author
  app.rb
  class/game.rb
  main.rb
  spec/game_spec.rb
Labels: Chandan's Task

#56 Milestone: Refactor movie and music album entry methods
  apps/game_app.rb
  apps/movie_app.rb
  apps/music_album_app.rb
  data/movies.json
  data/music_album.json
  main.rb
  schema.sql
Labels: Eloghene's Task

#57 Preserve data of Game & Author
  apps/game_app.rb
  data/author.json
  data/game.json
  main.rb
Labels: Chandan's Task

#58 Add options for Book & Label
  apps/book_app.rb
  main.rb
Labels: Melkammu's Task

#59 Create a schema.sql for Game & Author
  schema.sql
Labels: Chandan's Task

#60 Preserve data of Book and Label
  apps/book_app.rb
  apps/book_helper.rb
  data/books.json
  data/labels.json
  main.rb
Labels: Melkammu's Task

#62 Milestone: Add Authors and video presentation linnk to Readme file
  README.md
  data/books.json
  data/labels.json
  data/movies.json
  image.png
Labels: Eloghene's Task

#61 Create a schema.sql for Book & Label
  data/books.json
  data/labels.json
  main.rb
  schema.sql
Labels: Melkammu's Task
